# Generated by Django 3.2.9 on 2021-11-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nu_talker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutalker',
            name='bio',
            field=models.TextField(null=True),
        ),
    ]
